language: csharp
solution: OTAPI.sln
install:
  - mozroots --import --sync
  - nuget restore API/packages.config -PackagesDirectory packages/ -source "https://api.nuget.org/v3/index.json;https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/"
  - nuget restore Patcher/packages.config -PackagesDirectory packages/ -source "https://api.nuget.org/v3/index.json;https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/"
script:
  - xbuild /p:Configuration=Debug "OTAPI.sln"
